Repository ICEI-PUC-Minas-PMV-ADS/pmv-ads-2023-2-e1-proj-web-t1-clube-do-quadrinho, pull requests merged in 2023-11, with the labels that each got.

#46 Update code and folders
  codigo-fonte/src/assets/bootstrap/custom-theme.css
  codigo-fonte/src/assets/util/logout.js
  codigo-fonte/src/paginas/ListasQuadrinhos/Editar-listas.html
  codigo-fonte/src/paginas/ListasQuadrinhos/index.html
  codigo-fonte/src/paginas/ListasQuadrinhos/lista.html
  codigo-fonte/src/paginas/ListasQuadrinhos/script.js
  codigo-fonte/src/paginas/ListasQuadrinhos/style.css
  codigo-fonte/src/paginas/cadastro/cadastro-page.html
  codigo-fonte/src/paginas/login/login-page.css
  codigo-fonte/src/paginas/login/login-page.html
  codigo-fonte/src/paginas/paginaListas/editarLista/editar-lista.css
  codigo-fonte/src/paginas/paginaListas/editarLista/editar-lista.html
  codigo-fonte/src/paginas/paginaListas/index.html
  codigo-fonte/src/paginas/paginaListas/lista-style.css
  codigo-fonte/src/paginas/paginaListas/lista/lista.html
  codigo-fonte/src/paginas/paginaListas/lista/lista.js
  codigo-fonte/src/paginas/paginaListas/novaLista/nova-lista.html
  codigo-fonte/src/paginas/paginaListas/novaLista/nova-lista.js
  codigo-fonte/src/paginas/paginaListas/script.js
  codigo-fonte/src/paginas/paginaListas/style.css
  codigo-fonte/src/paginas/paginaQuadrinho/quadrinho-style.css
  codigo-fonte/src/paginas/paginaQuadrinho/quadrinho.html
  codigo-fonte/src/paginas/paginaQuadrinho/quadrinho.js
  codigo-fonte/src/services/account-service/account-service.js
  codigo-fonte/src/services/comics-service/comics-service.js
  codigo-fonte/src/services/lists-service/lists-service.js
Labels: documentation, development

#48 issue #47 e #45
  codigo-fonte/src/assets/util/search.js
  codigo-fonte/src/database/comicsDb.json
  codigo-fonte/src/env.js
  codigo-fonte/src/paginas/cadastro/cadastro-page.html
  codigo-fonte/src/paginas/login/login-page.html
  codigo-fonte/src/paginas/paginaListas/editarLista/editar-lista.html
  codigo-fonte/src/paginas/paginaListas/index.html
  codigo-fonte/src/paginas/paginaListas/novaLista/nova-lista.html
  codigo-fonte/src/paginas/paginaQuadrinho/quadrinho-style.css
  codigo-fonte/src/paginas/paginaQuadrinho/quadrinho.html
  codigo-fonte/src/paginas/paginaQuadrinho/quadrinho.js
  codigo-fonte/src/services/comics-service/comics-service.js
Labels: development

#52 add elementos visuais pagina de cadastro
  codigo-fonte/src/assets/bootstrap/custom-theme.css
  codigo-fonte/src/paginas/cadastro/cadastro-page.css
  codigo-fonte/src/paginas/cadastro/cadastro-page.html
  codigo-fonte/src/paginas/cadastro/cadastro-page.js
Labels: development

#60 Update login and logout
  codigo-fonte/src/assets/util/logout.js
  codigo-fonte/src/paginas/login/login-page.js
  codigo-fonte/src/paginas/paginaListas/novaLista/nova-lista.html
  codigo-fonte/src/paginas/paginaListas/novaLista/nova-lista.js
  codigo-fonte/src/paginas/paginaQuadrinho/quadrinho-style.css
  codigo-fonte/src/paginas/paginaQuadrinho/quadrinho.html
  codigo-fonte/src/paginas/paginaQuadrinho/quadrinho.js
  codigo-fonte/src/services/account-service/account-service.js
  codigo-fonte/src/services/comics-service/comics-service.js
  codigo-fonte/src/services/lists-service/lists-service.js
Labels: development

#59 desenvolvimento funcionalidade de avaliar quadrinhos
  codigo-fonte/src/paginas/paginaListas/novaLista/nova-lista.html
  codigo-fonte/src/paginas/paginaListas/novaLista/nova-lista.js
  codigo-fonte/src/paginas/paginaQuadrinho/quadrinho-style.css
  codigo-fonte/src/paginas/paginaQuadrinho/quadrinho.html
  codigo-fonte/src/paginas/paginaQuadrinho/quadrinho.js
  codigo-fonte/src/services/comics-service/comics-service.js
  codigo-fonte/src/services/lists-service/lists-service.js
Labels: development

#68 Elaboração de testes Thiago
  documentos/07-Plano de Testes de Software.md
Labels: documentation

#67 consertar navegação do menu, e func. de log-in
  codigo-fonte/src/paginas/Homepage/Homepage.html
  codigo-fonte/src/paginas/Homepage/Homepage.js
  codigo-fonte/src/paginas/login/login-page.js
  codigo-fonte/src/paginas/paginaListas/index.html
  codigo-fonte/src/services/account-service/account-service.js
Labels: development

#71 Feature/registro de execucao caso de teste
  documentos/08-Registro de Testes de Software.md
Labels: documentation

#72 bloqueio das telas quando não há usuario logado
  codigo-fonte/src/paginas/Homepage/Homepage.js
  codigo-fonte/src/paginas/paginaListas/editarLista/editar-lista.js
  codigo-fonte/src/paginas/paginaListas/lista/lista.js
  codigo-fonte/src/paginas/paginaListas/novaLista/nova-lista.js
  codigo-fonte/src/paginas/paginaListas/script.js
Labels: development

#77 Thiago bastani patch 1
  documentos/08-Registro de Testes de Software.md
Labels: documentation
